---
kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-configmap
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.traefik]
      address = ":8080"
      [entryPoints.http]
      address = ":80"
      #[entryPoints.http.redirect]
      #    entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]

    [api]
    entryPoint = "traefik"

    [kubernetes]

    [metrics]
      [metrics.prometheus]
      buckets=[0.1,0.3,1.2,5.0]
      entryPoint = "traefik"
    [log]

    # Log level
    #
    # Optional
    # Default: "ERROR"
    #
    level = "DEBUG"

    # Sets the filepath for the traefik log. If not specified, stdout will be used.
    # Intermediate directories are created if necessary.
    #
    # Optional
    # Default: os.Stdout
    #
    filePath = "/var/log/traefik.log"

    # Format is either "json" or "common".
    #
    # Optional
    # Default: "common"
    #
    # format = "json"

    ################################################################
    # Access logs configuration
    ################################################################

    # Enable access logs
    # By default it will write to stdout and produce logs in the textual
    # Common Log Format (CLF), extended with additional fields.
    #
    # Optional
    #
    [accessLog]
    
    # Sets the file path for the access log. If not specified, stdout will be used.
    # Intermediate directories are created if necessary.
    #
    # Optional
    # Default: os.Stdout
    #
    filePath = "/var/log/access.log"

    # Format is either "json" or "common".
    #
    # Optional
    # Default: "common"
    #
    format = "json"
    [accessLog.fields]
      defaultMode = "keep"

      [accessLog.fields.names]
        "ClientUsername" = "keep"

      [accessLog.fields.headers]
        defaultMode = "keep"

        [accessLog.fields.headers.names]
          "User-Agent" = "redact"
          "Authorization" = "keep"
          "Content-Type" = "keep"

